### ISSUE TITLE
DUNet Failed to Download.

### ISSUE THREAD

**Issue by arelhossan** [achaiah/pywick#21]
Hello,

I am trying to run your implementation of DUNet and it fails to initialize the model.

The code I ran was:
`from pywick.models.segmentation import DUNet_Resnet50

img = torch.randn(2, 3, 256, 256)
model = DUNet_Resnet50()
outputs = model(img)
`

which threw this error:

Model file /root/.torch/models/resnet50-25c4b509.pth is not found. Downloading.
Downloading /root/.torch/models/resnet50-25c4b509.zip from https://hangzh.s3.amazonaws.com/encoding/models/resnet50-25c4b509.zip...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-2f6831185f92> in <module>()
      1 img = torch.randn(2, 3, 256, 256)
----> 2 model = DUNet_Resnet50()
      3 outputs = model(img)

6 frames
/usr/local/lib/python3.7/dist-packages/pywick/models/segmentation/dunet.py in DUNet_Resnet50(num_classes, **kwargs)
    138 
    139 def DUNet_Resnet50(num_classes=1, **kwargs):
--> 140     return get_dunet(num_classes=num_classes, backbone='resnet50', **kwargs)
    141 
    142 

/usr/local/lib/python3.7/dist-packages/pywick/models/segmentation/dunet.py in get_dunet(num_classes, backbone, pretrained, **kwargs)
    133         pretrained : bool (default: True) - whether to load pretrained backbone network, that was trained on ImageNet.
    134         """
--> 135     model = DUNet(num_classes=num_classes, backbone=backbone, pretrained=pretrained, **kwargs)
    136     return model
    137 

/usr/local/lib/python3.7/dist-packages/pywick/models/segmentation/dunet.py in __init__(self, num_classes, pretrained, backbone, aux, **kwargs)
     26 
     27     def __init__(self, num_classes, pretrained=True, backbone='resnet101', aux=False, **kwargs):
---> 28         super(DUNet, self).__init__(num_classes, pretrained=pretrained, aux=aux, backbone=backbone, **kwargs)
     29         self.head = _DUHead(2144, **kwargs)
     30         self.dupsample = DUpsampling(256, num_classes, scale_factor=8, **kwargs)

/usr/local/lib/python3.7/dist-packages/pywick/models/segmentation/da_basenets/segbase.py in __init__(self, num_classes, pretrained, aux, backbone, **kwargs)
     21         self.nclass = num_classes
     22         if backbone == 'resnet50':
---> 23             self.pretrained = resnet50_v1s(pretrained=pretrained, **kwargs)
     24         elif backbone == 'resnet101':
     25             self.pretrained = resnet101_v1s(pretrained=pretrained, **kwargs)

/usr/local/lib/python3.7/dist-packages/pywick/models/segmentation/da_basenets/resnetv1b.py in resnet50_v1s(pretrained, model_root, **kwargs)
    236     if pretrained:
    237         from .model_store import get_resnet_file
--> 238         model.load_state_dict(torch.load(get_resnet_file('resnet50', root=model_root)), strict=False)
    239     return model
    240 

/usr/local/lib/python3.7/dist-packages/pywick/models/segmentation/da_basenets/model_store.py in get_resnet_file(name, root)
     49     download(_url_format.format(repo_url=repo_url, file_name=file_name),
     50              path=zip_file_path,
---> 51              overwrite=True)
     52     with zipfile.ZipFile(zip_file_path) as zf:
     53         zf.extractall(root)

/usr/local/lib/python3.7/dist-packages/pywick/models/segmentation/da_basenets/download.py in download(url, path, overwrite, sha1_hash)
     66         r = requests.get(url, stream=True)
     67         if r.status_code != 200:
---> 68             raise RuntimeError("Failed downloading url %s"%url)
     69         total_length = r.headers.get('content-length')
     70         with open(fname, 'wb') as f:

RuntimeError: Failed downloading url https://hangzh.s3.amazonaws.com/encoding/models/resnet50-25c4b509.zip

The same happens with other DUNet backbones. I am not sure if other models have similar issues, but it seems to be a simple access problem.

**Comment by achaiah** [comment]
It looks like the base models are no longer available for download from the original source. Here is another place where the model can be downloaded from: https://github.com/LikeLy-Journey/SegmenTron/releases/download/v0.1.0/resnet50-25c4b509.pth
