### ISSUE TITLE
BCEDiceFocalLoss problem

### ISSUE THREAD

**Issue by liuzhiyangnku** [achaiah/pywick#7]
In the file, the dice is defined as a BCE loss, which seems to be wrong. 
   def __init__(self, l=0.5, weight_of_focal=1.):
        super(BCEDiceFocalLoss, self).__init__()
        # self.bce = BCELoss2d()
        # self.dice = SoftDiceLoss()
        self.dice = BCELoss2d()
        self.focal = FocalLoss(l=l)
        self.weight_of_focal = weight_of_focal

**Comment by achaiah** [comment]
Thanks for pointing that out. The issue has already been fixed in master. What release are you referring to?

**Comment by liuzhiyangnku** [comment]
Seems that the problem is still there if install from PIP.

**Comment by achaiah** [comment]
Yes, I haven't pushed a new version to PIPY yet. For now please install with PIP from git master. I will release a new version soon, just want to verify a few things before publishing.
