### ISSUE TITLE
Problem with PolyConv2d, forward fucntion

### ISSUE THREAD

**Issue by pykeras** [achaiah/pywick#9]
Hi, and thanks for your code
I just try to implement this on keras for a learning purpose, but as i do this i cannot understand `block_index`, so i think you forgot using for loop or how you pass block_index to it:

```
class PolyConv2d(nn.Module):
    def forward(self, x, block_index):
        x = self.conv(x)
        bn = self.bn_blocks[block_index]
        x = bn(x)
        x = self.relu(x)
        return x
```

please let me know if I was wrong about this one

**Comment by achaiah** [comment]
Hi,

Are you referring to polynet? If so, [the implementation is here](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/polynet.py), so you may want to ask the author.

Thanks
